version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "refresh-tableau-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-66t01v46pi7c"
s3_prefix = "refresh-tableau-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["RefreshTableauDevFunction=462560519018.dkr.ecr.eu-west-1.amazonaws.com/tableau-dev-refresh"]
