version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "handle-sf-request"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nw9mxc5emv1g"
s3_prefix = "handle-sf-request"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HandleSFFunction=486592736240.dkr.ecr.eu-west-2.amazonaws.com/handle-sf-request"]
