version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "run-rivery"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hi76rhor2v61"
s3_prefix = "run-rivery"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["RunRiveryFunction=486592736240.dkr.ecr.eu-west-1.amazonaws.com/run-rivery"]
