version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "error-handler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-66t01v46pi7c"
s3_prefix = "error-handler"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ErrorHandlerFunction=462560519018.dkr.ecr.eu-west-1.amazonaws.com/lambda-error"]
