version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "load-real-sf-contacts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hi76rhor2v61"
s3_prefix = "load-real-sf-contacts"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LoadRealSFContactsFunction=486592736240.dkr.ecr.eu-west-1.amazonaws.com/bulk-load-real-sf-contacts"]
