version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "billing-validation"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hi76rhor2v61"
s3_prefix = "billing-validation"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["BillingValidationsFunction=486592736240.dkr.ecr.eu-west-1.amazonaws.com/billing-validation"]
profile = "prod"
disable_rollback = true
